### ISSUE TITLE
bug(DatePicker): Type for `value` is incorrect

### ISSUE THREAD

**Issue by oliverchanyw** [opengovsg/design-system#100]
**Describe the bug**
- `DatePicker` accepts prop `value?: string | number | readonly string[] | undefined`, but it requires a `Date?`

**To Reproduce**
```tsx
      <Controller
        name="relative.dateOfBirth"
        render={() => (
          <DatePicker
            // @ts-expect-error - oh no
            value={new Date()}
          />
        )}
      />
```

**Expected behavior**
- TS should expect `Date?`

**Comment by karrui** [comment]
Looking at DatePicker, seems to correctly set the value prop as `value?: Date | null | undefined`. Might be your types?
No error in the story:
```ts
const Test = () => (
  <Controller
    name="relative.dateOfBirth"
    render={() => <DatePicker value={new Date()} />} // no error
  />
)
```
