### ISSUE TITLE
Update green colour palette

### ISSUE THREAD

**Issue by khaleedah** [opengovsg/design-system#149]
**Current green looks a bit dated and old school**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/87360573/209746584-4bc79b24-c348-430f-91d2-5f580daef7bc.png">

**Update to a new green palette**
<img width="941" alt="image" src="https://user-images.githubusercontent.com/87360573/209746896-a4a27735-2b0c-44ab-a68e-67614265b16b.png">

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/87360573/209746877-8f6d3538-1d87-4f22-98c1-b3b9e0e1622e.png">

**Comment by karrui** [comment]
closed by #160
