### ISSUE TITLE
Storybook docs showing Chakra components as [object Object]

### ISSUE THREAD

**Issue by JasonChong96** [opengovsg/design-system#30]
**Describe the bug**
Storybook docs show chakra components as [object Object] instead "Show code"
![image](https://user-images.githubusercontent.com/35889982/150928073-58c3e8f4-85d1-447f-ab32-cd4c4a526cbe.png)

Seems to be a bug with Storybook
https://github.com/storybookjs/storybook/issues/16329

**To Reproduce**
1. Go to [storybook](https://design.hack.gov.sg/?path=/docs/components-badge--solid)
2. Click on "Show code" under subtle colors

**Expected behavior**
Chakra components being correctly labelled

**Comment by philippeaka** [comment]
I have encountered the same bug, a temporary fix would be to create a file and export chakra components like below : 
```javascript
import {
  Box as ChakraBox,
  Grid as ChakraGrid,
  GridItem as ChakraGridItem,
} from "@chakra-ui/react"

export const Box = ChakraBox
export const Grid = ChakraGrid
export const GridItem = ChakraGridItem
```

When you import Chakra components from this file in your stories, it should behave correctly in Storybook. 
It's not very clean,  but at least your user will know which components you are using.

**Comment by karrui** [comment]
Not sure if is has been fixed via some storybook package update (since we lost docs for a while due to upgrading to v7 in #151), but its definitely fixed once https://github.com/opengovsg/design-system/pull/179 is merged. Closing~
