### ISSUE TITLE
SingleSelect blank label has weird height

### ISSUE THREAD

**Issue by cyiafn** [opengovsg/design-system#397]
**Describe the bug**
If SingleSelect has a record with a blank label, it doesn't have proper height on hover.

**To Reproduce**
pass items in as such:
```ts
items: [
    {
      label: '',
      value: '',
    },
  ]
```

**Expected behavior**
Option of normal height

**Screenshots**
<img width="429" alt="image" src="https://github.com/opengovsg/design-system/assets/5841923/72859849-487f-4473-a707-05bb8b2d3449">
<img width="278" alt="image" src="https://github.com/opengovsg/design-system/assets/5841923/411f1169-4b15-4dae-8fa9-68723c71476b">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version Version 114.0.5735.106 (Official Build) (arm64)
 
**Additional context**

**Comment by karrui** [comment]
Is there a valid use case for this scenario?

**Comment by cyiafn** [comment]
We have a use case where the item defaults to a placeholder which is blank, which is how we encounter the issue.

**Comment by karrui** [comment]
> We have a use case where the item defaults to a placeholder which is blank, which is how we encountered the issue.

We have a placeholder property, is there a need to set the item to a blank selected item?

**Comment by karrui** [comment]
Would say that there are probably better options in terms of UX already accounted for, but your expected behaviour is technically still an easy fix if needed, haha!
