### ISSUE TITLE
[Bug] Wrong typing for components which previously had `useMarkdown`

### ISSUE THREAD

**Issue by seaerchin** [opengovsg/design-system#440]
**Describe the bug**
Old components which had the `useMarkdown` option had their `children` prop changed to accept `string & ReactNode`. This means that, in practice, only **string** will be accepted as children, not other react nodes.

**To Reproduce**
1. Create a `FormLabel.Description`
2. Put the children as `{2}` 
3. Observe that ts complains about typing

**Expected behavior**
No ts error, `number` is acceptable as `ReactNode`

**Code block**
```ts
<FormLabel.Description color="text.description">
  {2}
</FormLabel.Description>
```

**Comment by karrui** [comment]
seems to no longer be the case, closing issue. feel free to reopen if you have another example!
