### ISSUE TITLE
Extra padding under tag row in Multiselect

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/design-system#496]
When selecting a few tags and just nice there's a line break but there's no tag then there will be some extra padding underneath. Can remove?

<img width="622" alt="Screenshot 2023-09-19 at 10 26 10 AM" src="https://github.com/opengovsg/design-system/assets/28617936/e8678754-c9b7-447e-8fc8-0df3c543aa98">

**Comment by karrui** [comment]
Not be easily removed since we are using flex gap (i.e. to restyle everything with margin will not be worth it). At certain widths it will occur.
