### ISSUE TITLE
New Input variant: Hidden

### ISSUE THREAD

**Issue by pearlyong** [opengovsg/design-system#596]
Useful for password/token/key fields
[Figma here](https://www.figma.com/file/40SFxTL0j4xJTnU974t5v7/%5BOGP%5D-Base-Design-System?type=design&node-id=774-2714&mode=design&t=8F2la5xHxfmnIxIg-4)

Designer: @bookwormsuf

**Comment by karrui** [comment]
Unnecessary implementation (thought this was something like a [Pin Input](https://ark-ui.com/docs/components/pin-input))

Engineers just need to add a `type='password'` property onto an input and that will automatically become a password input field.

FYI @pearlyong
