### ISSUE TITLE
Toggle design is different from expected on design system

### ISSUE THREAD

**Issue by dcshzj** [opengovsg/design-system#82]
**Describe the bug**
The design for the Toggle component is different from what is expected on the OGP design system storybook.

**To Reproduce**
1. Set up a React project
2. Make use of the Toggle component
3. Realize that it is different from how it looks like on the OGP design system storybook

A sample application is available here: https://stackblitz.com/edit/react-ts-tpf2jf

**Expected behavior**
The Toggle component should look similar to the Switch component in Chakra UI, or at least looks like how it is on the [OGP design system storybook](https://design.hack.gov.sg/?path=/docs/components-toggle--toggle-states):

![Screenshot 2022-09-06 at 16 52 02](https://user-images.githubusercontent.com/27919917/188591679-85d712db-9ffb-4a20-974e-6a2f31b93402.png)

**Screenshots**
This is how the Toggle component looks like right now:

<img width="200" alt="Screenshot 2022-09-06 at 09 59 48" src="https://user-images.githubusercontent.com/27919917/188531185-668ddd08-05c5-426e-b870-698cd45571ef.png">
<img width="197" alt="Screenshot 2022-09-06 at 10 00 33" src="https://user-images.githubusercontent.com/27919917/188531257-8cca3a00-eb25-4329-8229-01b2b54f90ec.png">

**Additional context**
We are trying to use the Toggle component within the Isomer CMS but currently, we are using the Switch component from Chakra UI directly.

**Comment by karrui** [comment]
why

**Comment by seaerchin** [comment]
i can take a look at it!

**Comment by karrui** [comment]
sorry for the wait. seems to be fixed in #133.

![Screenshot 2022-12-22 at 1 50 29 PM](https://user-images.githubusercontent.com/22133008/209066387-ee4b5037-c890-44c4-bf6a-73528a872148.png)

Will be a minor version bump instead of patch though, some breaking changes.
