### ISSUE TITLE
bug(DateInput): Popover does not respect `isDisabled`

### ISSUE THREAD

**Issue by oliverchanyw** [opengovsg/design-system#88]
**Describe the bug**
Adding `isDisabled={true}` renders the `Input` disabled as expected, but not the picker. Changes can still be made

Uploading Screen Recording 2022-09-15 at 7.07.50 PM.mov…

**To Reproduce**
```tsx
<DateInput
  name={name}
  isDisabled={true}
  value="2022-08-08"
/>
```

**Expected behavior**
Disabled picker

**Comment by karrui** [comment]
Fixed in latest `alpha` build. See https://design.hack.gov.sg/?path=/story/components-datepicker--date-picker-disabled
