### ISSUE TITLE
bug(RestrictedFooter): undefined containerProps overwrites default values

### ISSUE THREAD

**Issue by wenhaogoh** [opengovsg/design-system#90]
**Describe the bug**
The usage of `containerProps` in `RestrictedFooter` is rather unintuitive due to how they overwrite design system's default values. For example, a user may want to set the `px` field to some value given a condition but fallback to design system's default value if otherwise. Intuitively, this should work:

```tsx
    <RestrictedFooter
      appLink={window.location.origin}
      appName={APP_NAME.full}
      textColorScheme="white"
      containerProps={{ px: condition ? value : undefined}}
      footerLinks={FOOTER_LINKS}
    />
```

However, as [keys with undefined values are not filtered before overwriting the props](https://github.com/opengovsg/design-system/blob/main/react/src/RestrictedFooter/RestrictedFullFooter.tsx#L133), `px` falls back to Chakra's default value instead. One would have to do this instead:

```tsx
    const containerProps = condition ? { px: value } : {} // or undefined
    <RestrictedFooter
      appLink={window.location.origin}
      appName={APP_NAME.full}
      textColorScheme="white"
      containerProps={containerProps}
      footerLinks={FOOTER_LINKS}
    />
```

**Expected behavior**
Setting keys with undefined value should fall back to design system's default values rather than Chakra's.

**Comment by karrui** [comment]
Updated in #133 to use colormode handling
